### ISSUE TITLE
Installation of docker-compose failed

### ISSUE THREAD

**Issue by nqb** [lefilament/ansible_role_docker_server#4]
Hello,

Starting from `docker-compose` 1.28.4, it's not possible to install it without a `pip` up-to-date due to requirements on `cryptography` Python library (see https://github.com/docker/compose/issues/8105 and https://github.com/pyca/cryptography/issues/5753)

On Ubuntu 18.04 with pip3 (9.0.1), even if you installed [Rust toolchain](https://github.com/pyca/cryptography/blob/main/docs/installation.rst#debianubuntu), you still got this error during installation of `docker-compose`:

```
  Collecting cryptography>=2.5 (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<5,>=4.4.4->docker-compose)
      Using cached https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-nqlyx_qm/cryptography/setup.py", line 14, in <module>
            from setuptools_rust import RustExtension
        ModuleNotFoundError: No module named 'setuptools_rust'
  
                =============================DEBUG ASSISTANCE==========================
                If you are seeing an error here please try the following to
                successfully install cryptography:
  
                Upgrade to the latest pip and try again. This will fix errors for most
                users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                =============================DEBUG ASSISTANCE==========================
```

My workaround was to pin `docker-compose` to 1.28.3 (dependent to `cryptography` 3.3.2 which doesn't require a recent `pip` version).

I don't test if  `pip3 install setuptools_rust docker-compose` works

**Comment by remi-filament** [comment]
Since this is working with Ubuntu 20.04, I would prefer to update pip to latest version instead.
I did it in 4c97849d7ead09602c2059709fbc30c4f23099a3
Could you please let me know if this fixes your issue ?

**Comment by nqb** [comment]
Hello @remi-filament,

It doesn't work like this because, in fact, Ansible runs:

```
  - /usr/bin/pip3
  - install
  - -U
  - pip
  - docker-compose
```

which means `pip` is still at older version when downloading `cryptography` dependency.

I tried to install `setuptools-rust` using `pip` before installing `docker-compose` and it works. i'm much in favor of such solution because after upgrading `pip` like you proposed, we have a `python3-pip` package that doesn't match current `pip` version.

**Comment by remi-filament** [comment]
I prefer to have an up-to-date pip environment (even if higher than the one distributed by OS) rather than installing extra dependencies that I would have to maintain afterwards.
You are right my previous commit was not enough, I updated the role and tested OK yesterday on new server installation here : 60c3f0cc66375ed16c35c808b3790e3117a0ffa8
